Fix compile: add missing QImage include
/home/milian/projects/kf5/src/kde/pim/kdepim-apps-libs/kaddressbookgrantlee/src/printing/contactgrantleeprintobject.cpp:257:74: error: invalid use of incomplete type ‘class QImage’